"""
features/home_automation.py — voice-controlled relay switches (ESP32 boards),
wired into the hub exactly like any other feature (lidar, OCR, money): it is
selected by its own gesture/voice command from the ACTIVE menu, and each
relay is its OWN separate Feature (RelaySwitch) with its own bindable gesture,
so it shows up in enrollment and the Programmable panel automatically — no
gesture_hub changes needed at all.

The ESP32 relay board never talks to the OrangePi directly — see
server_app/handlers/home.py and server_app/esp_relay_firmware/. The OrangePi's
only two jobs here are:
  1. Toggling relays through the server (feature="home", action="toggle").
  2. One-time pairing — scanning the WiFi-setup QR code (generated by the
     server) with its own camera and handing the decoded credentials to the
     ESP32's temporary setup access point.
"""

import json
import os
import subprocess
import time
import urllib.parse
import urllib.request

import orangepi_client as mc            # reused unchanged, exactly like money_recognition.py
from features.base import Feature, FeatureContext
from features.money_recognition import MoneyRecognition
import metrics

# ── Direct relay control (OrangePi → ESP relay board over the LAN) ────────────
# The ESP exposes  GET http://<ip>/relay?ch=N&state=on|off|toggle  and
# GET http://<ip>/status. We cache the board's IP here so the Pi can drive the
# relays DIRECTLY, without the laptop server in the control loop. The IP is
# learned from the server once (action "get_relays") and/or set by hand in this
# file. Delete the file to force a refresh.
RELAY_CACHE_PATH   = os.path.expanduser("~/.relay_board.json")
RELAY_HTTP_TIMEOUT = 3.0


def _load_relay_cache() -> dict:
    try:
        with open(RELAY_CACHE_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _save_relay_cache(info: dict) -> None:
    try:
        with open(RELAY_CACHE_PATH, "w", encoding="utf-8") as f:
            json.dump(info, f, indent=2)
    except OSError as e:
        print(f"[HOME] relay cache write failed: {e}")


def _refresh_relay_ip(link) -> "dict | None":
    """Ask the server for the paired board's IP and cache it. Returns the
    cached info dict {ip, device_id, relay_count} or None."""
    if link is None:
        return None
    try:
        resp = link.send("home", {"action": "get_relays"})
    except Exception as e:
        print(f"[HOME] get_relays failed: {e}")
        return None
    devices = (resp or {}).get("devices") or []
    if not devices:
        return None
    d = devices[0]                       # most-recently-seen board
    if not d.get("ip"):
        return None
    info = {"ip": d["ip"], "device_id": d.get("device_id"),
            "relay_count": d.get("relay_count", 2)}
    _save_relay_cache(info)
    return info


def _relay_board_ip(link, refresh: bool = False) -> "str | None":
    """Best-known relay board IP: cache first, else fetch from the server."""
    if not refresh:
        ip = _load_relay_cache().get("ip")
        if ip:
            return ip
    info = _refresh_relay_ip(link)
    return info.get("ip") if info else _load_relay_cache().get("ip")


def _relay_direct(ip: str, ch: int, state: str) -> "dict | None":
    """GET http://<ip>/relay?ch=<ch>&state=<state>. Returns the ESP's JSON
    ({"ok":true,"state":"on"}) or None on any failure."""
    url = f"http://{ip}/relay?ch={ch}&state={urllib.parse.quote(state)}"
    try:
        with urllib.request.urlopen(url, timeout=RELAY_HTTP_TIMEOUT) as r:
            return json.loads(r.read().decode("utf-8"))
    except Exception as e:
        print(f"[HOME] direct relay call failed ({url}): {e}")
        return None

try:
    import cv2
    _CV2_OK = True
except Exception:
    _CV2_OK = False

CAMERA_INDICES    = [0, 1, 2]
QR_SCAN_TIMEOUT_S = 15.0

# transcribe()'s default initial_prompt/hotwords are money recognition's
# currency vocabulary, which actively biases Whisper's decoder away from
# unrelated words like "pair"/"status" -- see features/ocr_reader.py's
# OCR_INITIAL_PROMPT for the same fix applied there first.
HOME_INITIAL_PROMPT = (
    "Home automation voice commands. Words used: pair, setup, status, "
    "check, close, done, stop."
)
HOME_HOTWORDS = "pair setup status check close done stop"

# Must match server_app/esp_relay_firmware/relay_controller/relay_controller.ino
ESP_SETUP_SSID     = "RelayCtrl-Setup"
ESP_SETUP_PASSWORD = "relaysetup"
ESP_SETUP_URL      = "http://192.168.4.1/provision"

_PAIR_W   = {"pair", "add", "setup", "set up", "new device", "new relay"}
_STATUS_W = {"status", "state", "check"}
_CLOSE_W  = {"close", "done", "exit", "quit", "stop", "back"}


def _classify(text: str) -> str | None:
    if any(w in text for w in _CLOSE_W):
        return "CLOSE"
    if any(w in text for w in _PAIR_W):
        return "PAIR"
    if any(w in text for w in _STATUS_W):
        return "STATUS"
    return None


def _ensure_mc() -> None:
    """Load the shared voice stack once per process — reuses Money Recognition's
    flag so Whisper/cues/devices aren't loaded twice if that feature ran first."""
    if MoneyRecognition._models_ready:
        return
    mc.init_cues()
    mc.auto_detect_all()
    mc.load_models()
    MoneyRecognition._models_ready = True


def _parse_provision_data(data: str) -> "dict | None":
    """The server's QR now encodes a URL (http://192.168.4.1/provision?...)
    so a plain phone camera app can offer "open in browser" directly — see
    handlers/home.py's build_provision_url(). Accept that form here, but
    also fall back to legacy raw JSON in case an older QR is scanned."""
    try:
        payload = json.loads(data)
        if payload.get("type") == "esp_relay_provision":
            return payload
    except json.JSONDecodeError:
        pass

    try:
        parsed = urllib.parse.urlparse(data)
        if parsed.path == "/provision":
            q = {k: v[0] for k, v in urllib.parse.parse_qs(parsed.query).items()}
            if q.get("type") == "esp_relay_provision":
                q["server_home_port"] = int(q.get("server_home_port", 8090))
                q["relay_count"] = int(q.get("relay_count", 2))
                return q
    except Exception:
        pass
    return None


def _scan_qr(timeout_s: float = QR_SCAN_TIMEOUT_S) -> "dict | None":
    """Open the camera and look for the setup QR for up to timeout_s.
    Returns the decoded provisioning dict, or None if nothing legible was
    found in time (camera missing, no QR in view, or QR isn't ours)."""
    if not _CV2_OK:
        return None
    cap = None
    for idx in CAMERA_INDICES:
        c = cv2.VideoCapture(idx, cv2.CAP_V4L2)
        if c.isOpened():
            cap = c
            break
        c.release()
    if cap is None:
        return None

    detector = cv2.QRCodeDetector()
    deadline = time.time() + timeout_s
    try:
        while time.time() < deadline:
            ok, frame = cap.read()
            if not ok:
                continue
            data, _points, _straight = detector.detectAndDecode(frame)
            if not data:
                continue
            payload = _parse_provision_data(data)
            if payload is not None:
                return payload
    finally:
        cap.release()
    return None


def _active_wifi_profile() -> str | None:
    """Name of the currently active WiFi connection profile (NetworkManager),
    so the OrangePi can reconnect to its own network after the temporary
    switch to the ESP32's setup access point."""
    try:
        out = subprocess.run(
            ["nmcli", "-t", "-f", "NAME,TYPE", "connection", "show", "--active"],
            capture_output=True, text=True, timeout=5,
        ).stdout
        for line in out.splitlines():
            name, _, ctype = line.partition(":")
            if "wireless" in ctype or "wifi" in ctype:
                return name
    except Exception:
        pass
    return None


def _nmcli(*args, timeout: float = 20) -> bool:
    try:
        r = subprocess.run(["nmcli", *args], capture_output=True, text=True, timeout=timeout)
        return r.returncode == 0
    except Exception:
        return False


def _post_provision(payload: dict) -> bool:
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        ESP_SETUP_URL, data=body, headers={"Content-Type": "application/json"}, method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=6) as r:
            return r.status == 200
    except Exception:
        return False


class HomeAutomation(Feature):
    name = "home"
    title = "Home automation"

    def run(self, ctx: FeatureContext) -> None:
        fb, abort = ctx.feedback, ctx.abort

        t0 = time.time()
        _ensure_mc()
        metrics.report_load(ctx.link, self.name, (time.time() - t0) * 1000)

        fb.speak("Home automation. Say pair to set up a new relay board, "
                 "status to check relays, or close to exit.")
        fb.wait(timeout=8)   # let the opening finish before listening

        while not abort.is_set():
            text, _audit = mc.listen(initial_prompt=HOME_INITIAL_PROMPT,
                                     hotwords=HOME_HOTWORDS)
            if abort.is_set():
                break
            if not text:
                continue

            cmd = _classify(text)
            if cmd == "CLOSE":
                break
            elif cmd == "PAIR":
                self._pair(ctx)
            elif cmd == "STATUS":
                resp = ctx.link.send("home", {"action": "status"})
                fb.speak(resp["tts"] if resp else "Server not reachable.")
                fb.wait(timeout=6)
            else:
                fb.speak("Say pair, status, or close.")
                fb.wait(timeout=4)

    def _pair(self, ctx: FeatureContext) -> None:
        fb = ctx.feedback
        t0 = time.time()

        fb.speak("Show me the setup QR code now.")
        fb.wait(timeout=4)   # let the instruction finish before opening the camera
        payload = _scan_qr()
        if payload is None:
            fb.speak("No QR code found. Try again with better lighting.")
            fb.wait(timeout=5)
            metrics.report_action(ctx.link, self.name, "pair",
                                  (time.time() - t0) * 1000, ok=False, reason="no_qr")
            return

        fb.speak("QR code read. Connecting to the relay board now.")
        # The OrangePi's WiFi has to leave the home network briefly to reach
        # the ESP32's own setup access point — ServerLink transparently
        # reconnects once WiFi is restored below, so no other feature is
        # affected by this momentary drop.
        profile = _active_wifi_profile()
        joined  = _nmcli("device", "wifi", "connect", ESP_SETUP_SSID,
                         "password", ESP_SETUP_PASSWORD)
        ok = False
        if joined:
            time.sleep(1.0)   # let the interface settle before POSTing
            ok = _post_provision(payload)
        if profile:
            _nmcli("connection", "up", profile)

        if not joined:
            fb.speak("Could not connect to the relay board's setup network.")
        elif not ok:
            fb.speak("Could not send the WiFi details to the relay board. Your WiFi has been restored.")
        else:
            fb.speak("Relay board paired. It will join your WiFi and register with the server shortly.")
        fb.wait(timeout=6)

        # Only reachable again once WiFi is restored above, so this goes
        # through normally on the (now reconnected) server link.
        metrics.report_action(ctx.link, self.name, "pair", (time.time() - t0) * 1000,
                              ok=(joined and ok), device_id=payload.get("device_id"))


class RelaySwitch(Feature):
    """One instant on/off toggle, bound to its own gesture. Fires and returns
    immediately — there is no ongoing session, matching a light switch."""

    def __init__(self, relay_id: int, title: str):
        self.relay_id = relay_id
        self.name  = f"relay{relay_id}"
        self.title = title

    def run(self, ctx: FeatureContext) -> None:
        t0 = time.time()

        # ── PRIMARY: talk to the relay board DIRECTLY over the LAN ────────────
        ip = _relay_board_ip(ctx.link)
        if ip:
            resp = _relay_direct(ip, self.relay_id, "toggle")
            if resp is None:
                # Cached IP may be stale (board got a new DHCP lease) — refresh
                # from the server once and retry directly.
                ip = _relay_board_ip(ctx.link, refresh=True)
                if ip:
                    resp = _relay_direct(ip, self.relay_id, "toggle")
            if resp is not None and resp.get("ok"):
                state = resp.get("state", "?")
                ctx.feedback.speak(f"Relay {self.relay_id} turned {state}.")
                metrics.report_action(ctx.link, self.name, "toggle",
                                      (time.time() - t0) * 1000, ok=True)
                return

        # ── FALLBACK: let the server relay the command ────────────────────────
        resp = ctx.link.send("home", {"action": "toggle",
                                      "relay": self.relay_id, "state": "toggle"})
        if resp is None:
            # Do NOT also try to report this over the link: ServerLink just
            # reset the socket after a failed/blocking connect attempt, and a
            # metrics.report_action() call here would immediately trigger a
            # second blocking reconnect attempt on an already-unreachable
            # server — doubling the delay on what's meant to be an instant
            # light-switch gesture, for a metric that isn't worth that cost.
            ctx.feedback.speak("Relay not reachable.")
            return
        metrics.report_action(ctx.link, self.name, "toggle",
                              (time.time() - t0) * 1000, ok=True)
        ctx.feedback.speak(resp.get("tts", ""))
